### ISSUE TITLE
Listings with both 'start' and 'end' set are too slow.

### ISSUE THREAD

**Issue by slimndap** [slimndap/wp-theatre#91]
From the comments in #90:

> Something happened with the calendar widget. When activating this widget on a page, this increased the loadingtime of the page with 16 seconds. 
> There are around 60 productions, with around 350 events in the database.

> How can I speed this up? More seasons to split things up? Limit the output results? Paginate?

**Comment by PieterKruithof** [comment]
Thanks for looking in to this!

**Comment by slimndap** [comment]
Can you start by updating the plugin to the latest version (v0.10.6) and check if the problem is still there?

**Comment by PieterKruithof** [comment]
Done that, but has no effect.
Also done some testing to see what is slowing down. 
<ul>
<li>show only one month</li>
<li>show only one category</li>
<li>show only one month for one category</li>
<li>hide thumbnails</li>
<li>....</li>
</ul>
Looks like none of this has any effect. The script just has to check every event and thats taking a lot of time I think?

**Comment by slimndap** [comment]
Yes, it does have to lookup a lot of data.
However, I'm testing with 90 productions and 270 events and there are no performance issues.

Do you have this issue only when the calendar widget is showing?
Or is it also there when you are just showing your event with the shortcode that I gave you in #90?

**Comment by PieterKruithof** [comment]
Both. Happens with the calendar widget, and with [wpt_events] shortcode. 
Production listing is not to fast, but acceptable. The "Theater Voorstellingen" widget is also working acceptable.

Could this be due to the fact that I filter out all de css styling and divs in functions.php (like you explained earlier)?
For most shortcodes I have added filters like this:
<code>
/** title*/
	function replace_event_title_divs($html, $event) {return '<a href="'.$event->permalink().'">'.$event->title().'</a>';} add_filter('wpt_event_title_html','replace_event_title_divs', 10, 2);
</code>
I've done this for event remark, event datetime, event time, event date, custom endtime...

**Comment by PieterKruithof** [comment]
Could this be due to the fact that I filter out all de css styling and divs in functions.php (like you explained earlier)? For most shortcodes I have added filters. I've done this for event remark, event datetime, event time, event date, custom endtime...

edit: To bad... can not copy that filter code here somehow...

**Comment by slimndap** [comment]
It depends on what you are doing inside the `replace_event_title_divs` function. But I don't think this is the causing the performance issues. Is it possible to give me admin access to your test site?

**Comment by PieterKruithof** [comment]
Sure.. I will email it to you. Thanks.

**Comment by slimndap** [comment]
This is a known issue:
https://core.trac.wordpress.org/ticket/30044

The underlying query is becoming too complex for your server to handle. 
For now, the only way to fix this is to use either 'start' or 'end'. In your case:

`[wpt_events start="now" paginateby="month"] {{thumbnail|permalink}} {{title|permalink}} {{date}}{{time}} {{remark}} [/wpt_events]`

**Comment by slimndap** [comment]
And don't use the calendar widget on the same page.

**Comment by slimndap** [comment]
Pieter,

I just released an update for the Theater for WordPress plugin with a lot of performance improvement. 
This may have solved your issue.

Do you think you can recreate your original configuration and confirm if it's solved?
